version: "3"

volumes:
  database_data:
    driver: local

services:
  ################################
  #   Setup frontend container
  ################################
  frontend:
    build: ./
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
